recipient = "0x00000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8"
priv_key = "0x000000000000000000000000000000000000000000000000000000616c696365"
note_root = "0x154d6fd651e2292910ef1d6926ea46add7c87afef312975065ad1c3cebbd21ec"
index = "0"
note_hash_path = [
  "0x18d85f3de6dcd78b6ffbf5d8374433a5528d8e3bf2100df0b7bb43a4c59ebd63",
  "0x1b7ba1a4ebccefab74ac08030f380fbeb0a005c73c75069e4d08fbb67d4984b9",
  "0x0f40f15ccd167735cd35e2ee6390231f40433cf748434e7a0e8b26a95d96bf2d"
]
secret = "0x1929ea3ab8d9106a899386883d9428f8256cfedb3c4f6b66bf4aa4d28a79988f"

# note_root = "0x088747482267aba3922ed6a369dc673bac4807b90c4ba8a76ce64754bbe8601e"
# index = "1"
# note_hash_path = [
#   "0x2d5faf531a013e5891bdb166ff877f3d09d526351f2c78d78059bfa3a51c193b",
#   "0x06d4571fb9634e4bed32e265f91a373a852c476656c5c13b09bc133ac61bc5a6",
#   "0x11f1af5353964c0a18310badcf46c90c5393c43237f0cf8617c19b30a667c0bf"
# ]
# secret = "0x1929ea3ab8d9106a899386883d9428f8256cfedb3c4f6b66bf4aa4d28a79988f"

# {
#   recipient: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
#   priv_key: '0x000000000000000000000000000000000000000000000000000000616c696365',
#   note_root: '0x154d6fd651e2292910ef1d6926ea46add7c87afef312975065ad1c3cebbd21ec',
#   index: 0,
#   note_hash_path: [
#     '0x18d85f3de6dcd78b6ffbf5d8374433a5528d8e3bf2100df0b7bb43a4c59ebd63',
#     '0x1b7ba1a4ebccefab74ac08030f380fbeb0a005c73c75069e4d08fbb67d4984b9',
#     '0x0f40f15ccd167735cd35e2ee6390231f40433cf748434e7a0e8b26a95d96bf2d'
#   ],
#   secret: '0x1929ea3ab8d9106a899386883d9428f8256cfedb3c4f6b66bf4aa4d28a79988f'
# }
