setpub = []
recipient = "0x00000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8"
note_root = "0x165cdc3cbcf4a6bf7b69514807409a3ed2e701556821f396ca04781a6434d96a"
# return = [
#     "0x1fa077bf4c787f858e0f3a7fa031ff11f200a0ccc6e549c6af98ec96800af340",
#     "0x0c25956c07e2277e75f1ca10bae32c29f24b27f25625fe9258cec29dc90651dd"
# ]
# return = [
#     "0x1fa077bf4c787f858e0f3a7fa031ff11f200a0ccc6e549c6af98ec96800af340",
#     "0x00000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8",
# ]
return = "0x1fa077bf4c787f858e0f3a7fa031ff11f200a0ccc6e549c6af98ec96800af340"
